version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: aid-backend-image
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - .:/app
    tty: true
    environment:
      MONGODB_URI: "${MONGODB_URI}"
    
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URI: "${MONGODB_URI}"
