db = db.getSiblingDB('auth');

const usersData = [
  {
      "userID": "example1@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "2001-01-01",
      "currentSemester": 4,
      "currentStatus": "재학",
      "incomeLevel": 3,
      "lastGPA": 4.0,
      "totalGPA": 3.8,
      "major": "소프트웨어학과",
      "region": "서울",
      "savedScholarship": [1, 3, 10]
  },
  {
      "userID": "example2@skku.edu",
      "userPassword": "1398",
      "gender": false,
      "birthday": "1999-02-15",
      "currentSemester": 9,
      "currentStatus": "휴학",
      "incomeLevel": 0,
      "lastGPA": 3.7,
      "totalGPA": 3.5,
      "major": "경영학과",
      "region": "경기도",
      "savedScholarship": [5, 12, 19]
  },
  {
      "userID": "example3@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "2000-05-21",
      "currentSemester": 6,
      "currentStatus": "수료",
      "incomeLevel": 2,
      "lastGPA": 4.2,
      "totalGPA": 3.9,
      "major": "전자전기공학과",
      "region": "부산",
      "savedScholarship": [9, 15, 21]
  },
  {
      "userID": "example4@skku.edu",
      "userPassword": "1398",
      "gender": false,
      "birthday": "2002-08-10",
      "currentSemester": 2,
      "currentStatus": "재학",
      "incomeLevel": 5,
      "lastGPA": 3.5,
      "totalGPA": 3.2,
      "major": "화학공학과",
      "region": "광주",
      "savedScholarship": [2, 17, 28]
  },
  {
      "userID": "example5@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "2001-04-03",
      "currentSemester": 5,
      "currentStatus": "재학",
      "incomeLevel": 7,
      "lastGPA": 3.9,
      "totalGPA": 3.7,
      "major": "경제학과",
      "region": "인천",
      "savedScholarship": [3, 11, 25]
  },
  {
      "userID": "example6@skku.edu",
      "userPassword": "1398",
      "gender": false,
      "birthday": "2000-11-27",
      "currentSemester": 7,
      "currentStatus": "재학",
      "incomeLevel": 2,
      "lastGPA": 4.3,
      "totalGPA": 3.9,
      "major": "건축학과",
      "region": "대전",
      "savedScholarship": [8, 16, 27]
  },
  {
      "userID": "example7@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "1998-03-22",
      "currentSemester": 9,
      "currentStatus": "휴학",
      "incomeLevel": 1,
      "lastGPA": 3.4,
      "totalGPA": 3.6,
      "major": "물리학과",
      "region": "울산",
      "savedScholarship": [4, 18, 29]
  },
  {
      "userID": "example8@skku.edu",
      "userPassword": "1398",
      "gender": false,
      "birthday": "1999-07-30",
      "currentSemester": 8,
      "currentStatus": "재학",
      "incomeLevel": 4,
      "lastGPA": 3.8,
      "totalGPA": 3.6,
      "major": "화학과",
      "region": "강원도",
      "savedScholarship": [13, 19, 24]
  },
  {
      "userID": "example9@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "2000-10-12",
      "currentSemester": 3,
      "currentStatus": "재학",
      "incomeLevel": 8,
      "lastGPA": 4.1,
      "totalGPA": 3.8,
      "major": "컴퓨터공학과",
      "region": "충청남도",
      "savedScholarship": [5, 14, 20]
  },
  {
      "userID": "example10@skku.edu",
      "userPassword": "1398",
      "gender": true,
      "birthday": "2002-01-18",
      "currentSemester": 1,
      "currentStatus": "재학",
      "incomeLevel": 6,
      "lastGPA": 3.6,
      "totalGPA": 3.5,
      "major": "영문학과",
      "region": "대구",
      "savedScholarship": [6, 22, 26]
  }
]


const scholarshipData = [
    {
        "scholarshipTitle": "2024년 DB김준기문화재단 금융수리 장학생 4기 선발안내",
        "scholarshipName": "금융수리 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": 3.0,
        "compTotalGPA": true,
        "eligibleSemesters": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8
        ],
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-06 ~ 2024-12-30",
        "scholarshipAmount": "학기당 100만원, 최대 4회 수혜 가능",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "장학금 신청서",
            "학업계획서",
            "개인정보 수집 및 이용 동의서",
            "보험계리사 1차 합격사실확인서",
            "재학증명서"
        ],
        "applicationMethod": "메일 제출",
        "significant": "필수 모임활동 이수",
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122227&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "DB김준기문화재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "[재공지] [1398TF팀]2024학년도 수원지역동문회 장학생 선발 안내(~11/20)",
        "scholarshipName": "수원지역동문회 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": 3.0,
        "compTotalGPA": true,
        "eligibleSemesters": [
            3,
            4,
            5,
            6,
            7,
            8
        ],
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": [
            "수원시",
            "오산시",
            "화성시",
            "의왕시",
            "군포시"
        ],
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-07 ~ 2024-11-20",
        "scholarshipAmount": "1인당 150만원",
        "numberOfRecipients": 3,
        "requiredDocuments": [
            "장학금 신청서",
            "자기소개서",
            "성적표",
            "주민등록등본",
            "가족관계증명서",
            "건강보험료납입증명서"
        ],
        "applicationMethod": "메일 제출",
        "significant": "송년의밤 행사 참석 필수",
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121750&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "수원장학회",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "[한국장학재단] 2025학년도 1학기 국가장학금 1차 신청 기간 안내(11/21~12/26) (☆재학생 반드시 신청!)",
        "scholarshipName": "국가장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "소득 기반 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-21 ~ 2024-12-26",
        "scholarshipAmount": null,
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "온라인 신청",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122269&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "한국장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024년 2학기 삼공장학재단 장학생 추가 선발 안내 (~2024.11.22. 오전9시까지)",
        "scholarshipName": "삼공장학재단 장학금",
        "eligibleMajors": [
            "기계공학부",
            "화학공학/고분자시스템공학부",
            "신소재공학부",
            "건설환경공학부",
            "시스템경영공학과",
            "나노공학과"
        ],
        "minimumGPARequirement": 3.0,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-08 ~ 2024-11-22",
        "scholarshipAmount": "한 학기 전액 등록금",
        "numberOfRecipients": 6,
        "requiredDocuments": [
            "장학생 추천서",
            "장학금 지급 신청서",
            "가족관계증명서",
            "주민등록등본",
            "한국장학재단 학자금지원구간통지서",
            "성적증명서"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122275&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "삼공장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025학년도 에몬스가구 17기 장학생 선발 안내",
        "scholarshipName": "에몬스가구 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": 3.5,
        "compTotalGPA": true,
        "eligibleSemesters": [
            3,
            4,
            5,
            6
        ],
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": 24,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-11 ~ 2024-12-06",
        "scholarshipAmount": "500만원",
        "numberOfRecipients": 20,
        "requiredDocuments": [
            "장학생 지원서",
            "장학생 추천서",
            "성적 증명서",
            "재학 증명서",
            "가족관계 증명서",
            "소득 분위 통지서"
        ],
        "applicationMethod": "온라인 지원 및 우편 접수",
        "significant": "장학금 증서 수여식 참석 필수",
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122282&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "에몬스가구",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "[한국장학재단] 2024학년도 국가근로장학사업 동계방학 집중근로 프로그램 희망근로지 신청 안내",
        "scholarshipName": "국가근로장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "근로 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-11 ~ 2024-11-20",
        "scholarshipAmount": "시간당 12,220원",
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "한국장학재단 홈페이지",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122300&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "한국장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025년도 관정이종환교육재단 국내대학(원) 장학생 모집 안내",
        "scholarshipName": "관정이종환교육재단 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": 3.8,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": 24,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-14 ~ 2024-12-03",
        "scholarshipAmount": "최대 2,400만원",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "지원서",
            "자기소개서",
            "지도교수 추천서",
            "학업 관련 증빙서류",
            "어학능력증명서",
            "각종 활동 및 자격에 대한 증빙서류",
            "주민등록 등본",
            "가족관계 증명서",
            "소득수준 심사 서류"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122358&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "관정이종환교육재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024년 2학기 유한재단 결손/다문화가정 대상 장학생 추가 모집 안내",
        "scholarshipName": "유한재단 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": 5,
        "applicationPeriod": "2024-11-14 ~ 2024-11-27",
        "scholarshipAmount": "3,000,000원",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "장학생 신상카드",
            "개인정보동의서",
            "학자금 지원구간 통지서",
            "결손 및 다문화 가정임을 증명할 수 있는 서류"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122317&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "유한재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "[교육부지원 학부 장학사업 안내] [부트캠프사업단 참여 신청 안내]",
        "scholarshipName": "부트캠프 장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "교육 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-15 ~ 2024-11-30",
        "scholarshipAmount": null,
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "이메일 제출",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122414&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "부트캠프사업단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025-2026 헝가리 정부초청 장학생(Stipendium Hungaricum) 선발 안내",
        "scholarshipName": "헝가리 정부초청 장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-15 ~ 2025-01-15",
        "scholarshipAmount": null,
        "numberOfRecipients": 100,
        "requiredDocuments": null,
        "applicationMethod": "온라인 지원",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=122439&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": "헝가리 정부",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024년 2학기 소청장학재단 추가 장학생 모집안내 ( ~2024년 11월 15일 (금) 오전 9시까지)",
        "scholarshipName": "소청장학재단 장학생",
        "eligibleMajors": [
            "생명과학과"
        ],
        "minimumGPARequirement": 3.5,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-06 ~ 2024-11-15",
        "scholarshipAmount": "1,000,000원",
        "numberOfRecipients": 1,
        "requiredDocuments": [
            "추천서",
            "재학증명서",
            "성적증명서",
            "한국장학재단 학자금 지원구간 통지서",
            "교육비납입증명서",
            "학생 본인의 통장 사본"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121571&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "소청장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025학년도 유하푸른재단 제8기 장학생 모집 안내 (~2024년 11월 4일(월) 오전9시까지)",
        "scholarshipName": "유하푸른재단 장학생",
        "eligibleMajors": [
            "생명과학과"
        ],
        "minimumGPARequirement": 3.5,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-10-28 ~ 2024-11-04",
        "scholarshipAmount": "2백만원",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "지도교수 추천서",
            "지원서",
            "가족관계증명서",
            "성적증명서",
            "소득구간 통지서"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121620&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "유하푸른재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024년 2학기 소청장학재단 장학생 선발안내 (연장:~2024년 11월 05일 (화) 오전 9시까지)",
        "scholarshipName": "소청장학재단 장학생",
        "eligibleMajors": [
            "생명과학과"
        ],
        "minimumGPARequirement": 3.5,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-10-28 ~ 2024-11-05",
        "scholarshipAmount": "1,000,000원",
        "numberOfRecipients": 1,
        "requiredDocuments": [
            "추천서",
            "재학증명서",
            "성적증명서",
            "한국장학재단 학자금 지원구간 통지서",
            "교육비납입증명서",
            "학생 본인의 통장 사본"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121571&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "소청장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024-2학기 비교과 챌린지 장학금 시행 안내",
        "scholarshipName": "비교과 챌린지 장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-10-30 ~ 2024-12-20",
        "scholarshipAmount": "30~100만원",
        "numberOfRecipients": 160,
        "requiredDocuments": null,
        "applicationMethod": null,
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121768&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": null,
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024학년도 통영시 저소득 대학생 장학금 지원대상자 선발 안내",
        "scholarshipName": "통영시 저소득 대학생 장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": "C",
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": [
            "통영시"
        ],
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-10-31 ~ 2024-11-20",
        "scholarshipAmount": "최대 100만원",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "장학금 지급신청서",
            "기초생활수급자 또는 차상위계층 증명서",
            "재학증명서",
            "성적증명서",
            "생활기록부",
            "주민등록초본",
            "통장사본"
        ],
        "applicationMethod": "방문 또는 우편 신청",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121786&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "통영시",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024-2학기 복지 사각지대 학생 지원을 위한 학생성공-디딤돌장학금 신청 안내(~11/18)",
        "scholarshipName": "디딤돌장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-01 ~ 2024-11-18",
        "scholarshipAmount": "200만원 / 100만원",
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121788&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": null,
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025년도 KC 미래장학금 제8기 장학생 모집안내(~2025. 1. 10(금) 오전 9시까지)",
        "scholarshipName": "KC 미래장학금",
        "eligibleMajors": [
            "반도체",
            "첨단소재"
        ],
        "minimumGPARequirement": 3.0,
        "compTotalGPA": true,
        "eligibleSemesters": [
            3,
            4
        ],
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-01 ~ 2025-01-10",
        "scholarshipAmount": "학기별 수업료 전액 및 생활비 90만원",
        "numberOfRecipients": null,
        "requiredDocuments": [
            "장학생 지원서",
            "자기소개서",
            "타 장학금 수혜확인서",
            "학자금지원구간 통지서",
            "재학증명서",
            "성적증명서",
            "지도교수 날인 추천서",
            "개인정보 수집, 이용, 제공 동의서",
            "가족관계증명서",
            "건강보험료 납부 확인서",
            "지방세 세목별 과세 증명서"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121815&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "KC미래장학재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "DB김준기 문화재단 2024년 2학기 DB드림서포트장학생 선발안내 (연장:~2024년 11월 13일(수) 오전9시까지)",
        "scholarshipName": "DB드림서포트 장학생",
        "eligibleMajors": [
            "경영",
            "경제학과",
            "기계공학부",
            "화학공학/고분자시스템공학부",
            "신소재공학부",
            "건설환경공학부",
            "시스템경영공학과",
            "나노공학과"
        ],
        "minimumGPARequirement": 3.0,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": 2,
        "applicationPeriod": "2024-11-01 ~ 2024-11-13",
        "scholarshipAmount": "250만원",
        "numberOfRecipients": 7,
        "requiredDocuments": [
            "장학신청서",
            "추천서",
            "성적증명서",
            "학자금 지원구간 통지서"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121493&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "DB김준기문화재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024학년도 2학기 유한재단 유일한장학생(대학원) 추가모집안내 (~11월 8일(금) 오전 9시 까지)",
        "scholarshipName": "유일한장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "생활비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-01 ~ 2024-11-08",
        "scholarshipAmount": null,
        "numberOfRecipients": 1,
        "requiredDocuments": [
            "장학생 추천서",
            "학업계획서",
            "개인정보 동의서"
        ],
        "applicationMethod": "이메일 접수",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121822&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "유한재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024년 우양재단 동행장학생 선발 안내",
        "scholarshipName": "우양재단 동행장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "치료비 지원 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-04 ~ 2024-11-17",
        "scholarshipAmount": "100만원",
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "우양재단 홈페이지",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=121870&article.offset=10&articleLimit=10",
        "views": 0,
        "foundation": "우양재단",
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2025학년도 1학기 新대학원우수장학금 선발 안내(추천서 접수: ~10.10.(목))",
        "scholarshipName": "新대학원우수장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-10-08 ~ 2024-10-10",
        "scholarshipAmount": null,
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "대학원 학과 사무실",
        "significant": null,
        "link": "https://www.skku.edu/skku/campus/skk_comm/notice06.do?mode=view&articleNo=120988&article.offset=20&articleLimit=10",
        "views": 0,
        "foundation": null,
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024학년도 2학기 학문 후속세대 양성 장학금 신청 안내",
        "scholarshipName": "학문 후속세대 양성 장학금",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-04 ~ 2024-11-12",
        "scholarshipAmount": null,
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "이메일 제출",
        "significant": null,
        "link": "https://cse.skku.edu/cse/notice.do?mode=view&articleNo=182890&article.offset=0&articleLimit=10&srCategoryId1=1586",
        "views": 0,
        "foundation": null,
        "uploadedDate": "2024-11-15"
    },
    {
        "scholarshipTitle": "2024-2학기 학생성공 창의장학생 신청안내",
        "scholarshipName": "학생성공 창의장학생",
        "eligibleMajors": null,
        "minimumGPARequirement": null,
        "compTotalGPA": true,
        "eligibleSemesters": null,
        "scholarshipType": "등록금성 장학금",
        "ageLimit": null,
        "regionalRestrictions": null,
        "incomeLevelRequirement": null,
        "applicationPeriod": "2024-11-04 ~ 2024-11-12",
        "scholarshipAmount": null,
        "numberOfRecipients": null,
        "requiredDocuments": null,
        "applicationMethod": "이메일 제출",
        "significant": null,
        "link": "https://cse.skku.edu/cse/notice.do?mode=view&articleNo=182891&article.offset=0&articleLimit=10",
        "views": 0,
        "foundation": null,
        "uploadedDate": "2024-11-15"
    }
]

db.users.insertMany(usersData);
db.scholarships.insertMany(scholarshipsData);