name: Docker Test and Coverage

on:
  push:
    branches:
      - feat/jihun
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: test-image:latest

    - name: Run tests in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app test-image:latest /bin/bash -c "
          mongod --fork --logpath /var/log/mongodb.log &&
          source /usr/local/app/venv/bin/activate &&
          cd /app &&
          pip install pytest pytest-cov &&
          pytest --cov=src --cov-report=xml --cov-report=term
        "

    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        name: aid-backend-coverage
        fail_ci_if_error: true
